### ISSUE TITLE
README references nonexistent parameters for AWS

### ISSUE THREAD

**Issue by aimurphy** [harness-community/drone-docker-image-migration#9]
Under NOTES, it references `destination_username` and `destination_password`, but these are `username` and `password`.

Can you use `source_username` and `source_password` to set AWS ECR as the source?

**Comment by justAkshitAgrawal** [comment]
Sure, will update these

**Comment by justAkshitAgrawal** [comment]
Fix applied in PR: https://github.com/harness-community/drone-docker-image-migration/pull/10
